/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.43
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request for the /2/module/authenticate/authenticate API Request
 */
export interface AuthenticateAuthenticateV2Request { 
    /**
     * The customer code assigned to your account
     */
    pksCustomerCode: string;
    /**
     * The email address.
     */
    sEmailAddress?: string;
    /**
     * The Login name of the User.
     */
    sUserLoginname?: string;
    /**
     * A Password.  Must meet complexity requirements
     */
    sPassword: string;
}

