/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.42
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommonResponseObjDebug } from './commonResponseObjDebug';
import { CommonResponseObjDebugPayload } from './commonResponseObjDebugPayload';
import { CommonResponse } from './commonResponse';
import { EzsigndocumentGetObjectV1ResponseMPayload } from './ezsigndocumentGetObjectV1ResponseMPayload';


/**
 * Response for the /1/object/ezsigndocument/getDownloadUrl API Request
 */
export interface EzsigndocumentGetObjectV1Response { 
    mPayload: EzsigndocumentGetObjectV1ResponseMPayload;
    objDebugPayload?: CommonResponseObjDebugPayload;
    objDebug?: CommonResponseObjDebug;
}

