/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.44
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldEEzsignsignatureType } from './fieldEEzsignsignatureType';
import { EzsignsignatureRequest } from './ezsignsignatureRequest';


/**
 * An Ezsignsignature Object and children to create a complete structure
 */
export interface EzsignsignatureRequestCompound { 
    /**
     * The unique ID of the Ezsignfoldersignerassociation
     */
    fkiEzsignfoldersignerassociationID: number;
    /**
     * The page number in the document where to apply the signature
     */
    iEzsignpagePagenumber: number;
    /**
     * The X coordinate (Horizontal) where to put the signature block on the page.  Coordinate is calculated at 100dpi (dot per inch). So for example, if you want to put the signature block 2 inches from the left border of the page, you would use \"200\" for the X coordinate.
     */
    iEzsignsignatureX: number;
    /**
     * The Y coordinate (Vertical) where to put the signature block on the page.  Coordinate is calculated at 100dpi (dot per inch). So for example, if you want to put the signature block 3 inches from the top border of the page, you would use \"300\" for the Y coordinate.
     */
    iEzsignsignatureY: number;
    /**
     * The step when the Ezsignsigner will be invited to sign.
     */
    iEzsignsignatureStep: number;
    eEzsignsignatureType: FieldEEzsignsignatureType;
    /**
     * The unique ID of the Ezsigntemplate
     */
    fkiEzsigndocumentID: number;
}

