/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign application.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EzsigndocumentRequest } from './ezsigndocumentRequest';


/**
 * Request for the /1/object/ezsigndocument/editObject API Request
 */
export interface EzsigndocumentEditObjectV1Request { 
    objEzsigndocument?: EzsigndocumentRequest;
}

