/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.31
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The user type of the User for SSPR
 */
export type FieldEUserTypeSSPR = 'EzsignUser' | 'Native';

export const FieldEUserTypeSSPR = {
    EzsignUser: 'EzsignUser' as FieldEUserTypeSSPR,
    Native: 'Native' as FieldEUserTypeSSPR
};

