/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.37
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The user type of the User.
 */
export type FieldEUserType = 'AgentBroker' | 'Assistant' | 'Attendance' | 'Customer' | 'Employee' | 'Ezcom' | 'EzsignSigner' | 'EzsignUser' | 'FranchiseCustomerServer' | 'Normal' | 'RewardAdministration' | 'RewardMember' | 'RewardRepresentative' | 'RewardCustomer' | 'RewardDistributorServer' | 'Supplier' | 'VetrxCustomer' | 'Vetrxcustomergroup' | 'VetrxCustomerServer' | 'VetrxManufacturer' | 'VetrxVendor';

export const FieldEUserType = {
    AgentBroker: 'AgentBroker' as FieldEUserType,
    Assistant: 'Assistant' as FieldEUserType,
    Attendance: 'Attendance' as FieldEUserType,
    Customer: 'Customer' as FieldEUserType,
    Employee: 'Employee' as FieldEUserType,
    Ezcom: 'Ezcom' as FieldEUserType,
    EzsignSigner: 'EzsignSigner' as FieldEUserType,
    EzsignUser: 'EzsignUser' as FieldEUserType,
    FranchiseCustomerServer: 'FranchiseCustomerServer' as FieldEUserType,
    Normal: 'Normal' as FieldEUserType,
    RewardAdministration: 'RewardAdministration' as FieldEUserType,
    RewardMember: 'RewardMember' as FieldEUserType,
    RewardRepresentative: 'RewardRepresentative' as FieldEUserType,
    RewardCustomer: 'RewardCustomer' as FieldEUserType,
    RewardDistributorServer: 'RewardDistributorServer' as FieldEUserType,
    Supplier: 'Supplier' as FieldEUserType,
    VetrxCustomer: 'VetrxCustomer' as FieldEUserType,
    Vetrxcustomergroup: 'Vetrxcustomergroup' as FieldEUserType,
    VetrxCustomerServer: 'VetrxCustomerServer' as FieldEUserType,
    VetrxManufacturer: 'VetrxManufacturer' as FieldEUserType,
    VetrxVendor: 'VetrxVendor' as FieldEUserType
};

