/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.46
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Frequency at which reminders will be sent to signers that haven\'t signed the documents
 */
export type FieldEEzsignfolderSendreminderfrequency = 'None' | 'Daily' | 'Weekly';

export const FieldEEzsignfolderSendreminderfrequency = {
    None: 'None' as FieldEEzsignfolderSendreminderfrequency,
    Daily: 'Daily' as FieldEEzsignfolderSendreminderfrequency,
    Weekly: 'Weekly' as FieldEEzsignfolderSendreminderfrequency
};

