/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.45
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EzsignfolderRequest } from './ezsignfolderRequest';


/**
 * Request for the /1/object/ezsignfolder/editObject API Request
 */
export interface UNUSEDEzsignfolderEditObjectV1Request { 
    objEzsignfolder?: EzsignfolderRequest;
}

