export * from './globalCustomer.service';
import { GlobalCustomerService } from './globalCustomer.service';
export * from './moduleAuthenticate.service';
import { ModuleAuthenticateService } from './moduleAuthenticate.service';
export * from './moduleSspr.service';
import { ModuleSsprService } from './moduleSspr.service';
export * from './moduleUser.service';
import { ModuleUserService } from './moduleUser.service';
export * from './objectActivesession.service';
import { ObjectActivesessionService } from './objectActivesession.service';
export * from './objectApikey.service';
import { ObjectApikeyService } from './objectApikey.service';
export * from './objectEzsigndocument.service';
import { ObjectEzsigndocumentService } from './objectEzsigndocument.service';
export * from './objectEzsignfolder.service';
import { ObjectEzsignfolderService } from './objectEzsignfolder.service';
export * from './objectEzsignfoldersignerassociation.service';
import { ObjectEzsignfoldersignerassociationService } from './objectEzsignfoldersignerassociation.service';
export * from './objectEzsignsignature.service';
import { ObjectEzsignsignatureService } from './objectEzsignsignature.service';
export * from './objectFranchisebroker.service';
import { ObjectFranchisebrokerService } from './objectFranchisebroker.service';
export * from './objectFranchiseoffice.service';
import { ObjectFranchiseofficeService } from './objectFranchiseoffice.service';
export * from './objectFranchisereferalincome.service';
import { ObjectFranchisereferalincomeService } from './objectFranchisereferalincome.service';
export * from './objectPeriod.service';
import { ObjectPeriodService } from './objectPeriod.service';
export const APIS = [GlobalCustomerService, ModuleAuthenticateService, ModuleSsprService, ModuleUserService, ObjectActivesessionService, ObjectApikeyService, ObjectEzsigndocumentService, ObjectEzsignfolderService, ObjectEzsignfoldersignerassociationService, ObjectEzsignsignatureService, ObjectFranchisebrokerService, ObjectFranchiseofficeService, ObjectFranchisereferalincomeService, ObjectPeriodService];
